<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="classes" nsURI="http:///classes.ecore" nsPrefix="classes">
  <eSubpackages name="External" nsURI="http:///classes/External.ecore" nsPrefix="classes.External">
    <eClassifiers xsi:type="ecore:EClass" name="Payment">
      <eOperations name="validatePayment" ordered="false" lowerBound="1"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="Data" nsURI="http:///classes/Data.ecore" nsPrefix="classes.Data">
    <eClassifiers xsi:type="ecore:EClass" name="Reservation">
      <eOperations name="addRoom" ordered="false" lowerBound="1"/>
      <eOperations name="removeRoom" ordered="false" lowerBound="1"/>
      <eOperations name="createRes" ordered="false" lowerBound="1"/>
      <eOperations name="updateRes" ordered="false" lowerBound="1"/>
      <eOperations name="removeRes" ordered="false" lowerBound="1"/>
      <eOperations name="addPaymentDetails" ordered="false" lowerBound="1"/>
      <eOperations name="edirRoom" ordered="false" lowerBound="1"/>
      <eOperations name="validateResNr" ordered="false" lowerBound="1"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="arrDate" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="depDate" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="resNr" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="personDetails" ordered="false"
          lowerBound="1" eType="#//Business/PersonInfo"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="roommanage" ordered="false"
          lowerBound="1" eType="#//Data/RoomManage"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="statisticshandler" ordered="false"
          lowerBound="1" eType="#//Data/StatisticsHandler"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RoomManage">
      <eOperations name="createRoom" ordered="false" lowerBound="1">
        <eParameters name="room" ordered="false" lowerBound="1" eType="#//Data/roomInformation"/>
      </eOperations>
      <eOperations name="updateRoom" ordered="false" lowerBound="1">
        <eParameters name="room" ordered="false" lowerBound="1" eType="#//Data/roomInformation"/>
      </eOperations>
      <eOperations name="removeRoom" ordered="false" lowerBound="1">
        <eParameters name="room" ordered="false" lowerBound="1" eType="#//Data/roomInformation"/>
      </eOperations>
      <eOperations name="getRoomInfo" ordered="false" lowerBound="1" eType="#//Data/roomInformation">
        <eParameters name="roomNr" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eOperations name="checkIn" ordered="false" lowerBound="1">
        <eParameters name="arrDate" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="depDate" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="resNr" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eOperations name="CheckOut" ordered="false" lowerBound="1">
        <eParameters name="resNr" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="roomInfo" ordered="false"
          lowerBound="1" eType="#//Data/roomInformation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="roomdetails" ordered="false"
          lowerBound="1" eType="#//Data/roomInformation"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="checkinDate" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="checkoutDate" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="resNr" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="roomInformation">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bedsize" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="roomNr" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Availbility" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="AccessCard" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="roomType" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StaffDetails">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="phoneNr" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" ordered="false" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pass" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PaymentManagment">
      <eOperations name="isCardValid" ordered="false" lowerBound="1">
        <eParameters name="paymentDetails" ordered="false" lowerBound="1" eType="#//Business/PaymentDetails"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StatisticsHandler">
      <eOperations name="fetchReservations" ordered="false" lowerBound="1"/>
      <eOperations name="calculatePercentage" ordered="false" lowerBound="1"/>
      <eOperations name="GenerateDiagram" ordered="false" lowerBound="1"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ReservationNr" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="Business" nsURI="http:///classes/Business.ecore" nsPrefix="classes.Business">
    <eClassifiers xsi:type="ecore:EClass" name="ReservationHandler">
      <eOperations name="addRoom" ordered="false" lowerBound="1"/>
      <eOperations name="removeRoom" ordered="false" lowerBound="1"/>
      <eOperations name="addReservation" ordered="false" lowerBound="1"/>
      <eOperations name="updateReservation" ordered="false" lowerBound="1"/>
      <eOperations name="removeReservation" ordered="false" lowerBound="1"/>
      <eOperations name="EditRoom" ordered="false" lowerBound="1"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="arrDate" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="DepDate" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ReservationNr" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Person" ordered="false"
          lowerBound="1" upperBound="-1" eType="#//Business/PersonInfo"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Guests" ordered="false"
          lowerBound="1" upperBound="-1" eType="#//Business/PersonInfo"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="roomhandler" ordered="false"
          lowerBound="1" eType="#//Business/roomHandler"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="reservation" ordered="false"
          lowerBound="1" eType="#//Data/Reservation"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="roomHandler">
      <eOperations name="checkavailability" ordered="false" lowerBound="1"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="availability" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="roommanage" ordered="false"
          lowerBound="1" eType="#//Data/RoomManage"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CopyOf_Class1_1"/>
    <eClassifiers xsi:type="ecore:EClass" name="AccountHandler">
      <eOperations name="ValidateStaffInfo" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eParameters name="Id" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="pass" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="staffinfo" ordered="false"
          lowerBound="1" upperBound="-1" eType="#//Data/StaffDetails"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" ordered="false" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pass" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PaymentHandler">
      <eOperations name="makePayment" ordered="false" lowerBound="1">
        <eParameters name="paymentsDetails" ordered="false" lowerBound="1" eType="#//Business/PaymentDetails"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="paymentinfo" ordered="false"
          lowerBound="1" eType="#//Business/PaymentDetails"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="paymentmanagment" ordered="false"
          lowerBound="1" eType="#//Data/PaymentManagment"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="paymentdetails" ordered="false"
          lowerBound="1" eType="#//Business/PaymentDetails"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PaymentDetails">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="carsNr" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ccv" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="expMonth" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="expYear" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PersonInfo">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="irstName" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="adress" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="phoneNr" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="presentation" nsURI="http:///classes/presentation.ecore" nsPrefix="classes.presentation">
    <eClassifiers xsi:type="ecore:EClass" name="authentication">
      <eOperations name="logIn" ordered="false" lowerBound="1">
        <eParameters name="Id" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="pass" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="LogOut" ordered="false" lowerBound="1"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="accounthandler" ordered="false"
          lowerBound="1" eType="#//Business/AccountHandler"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="staffui" ordered="false"
          lowerBound="1" eType="#//presentation/StaffUI"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StaffUI">
      <eOperations name="searchRoomType" ordered="false" lowerBound="1">
        <eParameters name="roomType" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="price" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="arrvDate" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="depDate" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eOperations name="addRoom" ordered="false" lowerBound="1"/>
      <eOperations name="deleteRoom" ordered="false" lowerBound="1"/>
      <eOperations name="makeRes" ordered="false" lowerBound="1">
        <eParameters name="customerInfo" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="editRes" ordered="false" lowerBound="1">
        <eParameters name="resNr" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eOperations name="cancelRes" ordered="false" lowerBound="1"/>
      <eOperations name="getResInfo" ordered="false" lowerBound="1">
        <eParameters name="resNr" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="reservationhandler" ordered="false"
          lowerBound="1" eType="#//Business/ReservationHandler"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Customer">
      <eOperations name="searchRoomType" ordered="false" lowerBound="1"/>
      <eOperations name="makeRes" ordered="false" lowerBound="1"/>
      <eOperations name="editRes" ordered="false" lowerBound="1"/>
      <eOperations name="cancelRes" ordered="false" lowerBound="1"/>
      <eOperations name="getResInfo" ordered="false" lowerBound="1">
        <eParameters name="resNr" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eOperations name="getBill" ordered="false" lowerBound="1"/>
      <eOperations name="Operation1" ordered="false" lowerBound="1"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="reservationhandler" ordered="false"
          lowerBound="1" eType="#//Business/ReservationHandler"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="paymenthandler" ordered="false"
          lowerBound="1" eType="#//Business/PaymentHandler"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MainUI" abstract="true" interface="true"/>
  </eSubpackages>
</ecore:EPackage>
